### ISSUE TITLE
Schema examples question

### ISSUE THREAD

**Issue by undera** [chanced/openapi#6]
Hi,
I'm trying to work with the "examples" property of the `SchemaObj`, and I found that the `Examples` property is of type `RawMessage`, although the JSONSchema spec declares that it can only be array (reading here https://json-schema.org/understanding-json-schema/reference/generic.html).

Am I interpreting it wrong, or should the `Examples` property be a sort of "array of `RawMessage`", to simplify the interface of working with it?

**Comment by chanced** [comment]
Good catch. That has been updated and pushed. The tagged version is `0.0.7`.

Also, if you aren't dealing with references, you should be able to just resolve each of your types with a func that panics, warning about not supporting references yet. Doing so would avoid the need to switch on the kind.

I decided to pick up rust and grpc so I haven't finished the refactor. There isn't a whole lot left that needs to be done on it to get it to minimal working order. Mostly all that's left is finishing up the `Visitor` & implementing a `Visitor` which resolves all types into `Resolved{Type}`.

I'll probably circle back to it eventually but I apologize if you were expecting it.

**Comment by undera** [comment]
Thanks for the fix!
I already figured the `Resolver` and made my resolver fn's with `panic()`, just like you said.
Thanks for the library, it works well!
